# Use an official Python runtime as a parent image
FROM python:3.10-slim

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /mlflow/

# Install MLFLow and a MySQL client library for Python
RUN pip install mlflow[extras] psycopg2-binary boto3 cryptography pymysql
